name: metro_mate
description: "Your Metro Companion"
publish_to: 'DARSHAN BHALANI'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-195.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  photo_view: ^0.14.0
  google_maps_flutter: ^2.3.1
  dropdown_textfield: ^1.0.8
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  qr_flutter: ^4.1.0
  random_password_generator: ^0.2.1
  upi_india: ^3.0.1
  animated_splash_screen: ^1.3.0
  shared_preferences: ^2.2.0
  firebase_database: ^10.2.3
  firebase_storage: ^11.2.4
#  path_provider: ^2.0.15
  share: ^2.0.4
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
#  share_plus: ^7.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/maps/
    - assets/images/cities/

