import 'package:flutter/material.dart';
import 'package:metro_mate/Variables.dart';

class TermsofUsagePage extends StatelessWidget {
  const TermsofUsagePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Terms of Usage"),
        backgroundColor: PrimaryColor,
      ),
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 15,vertical: 12),
        child: ListView(
          children: [
            Text("\t\t\tIn terms of Information Technology statutes, this document is an electronic record. Being generated by a computer system it does not require any physical or digital signatures."),
            Text("\n\t\t\tThis document is published in accordance with the provisions of Information Technology regulations that require publishing the rules and regulations, privacy policy and Terms of Service for access or usage of:"),
            Text("\t\t\t“You” or “User” “Customer” shall mean any natural or legal person who has agreed to become a user of the Application by logging into the Application. The Application also provides certain services without registration/acceptance, and such provision of services does not absolve You of this contractual relationship."),
            Text("\t\t\t“We”, “Us”, “Our”, ‘Company’ shall mean Transhelp Technologies Pvt Ltd."),
            Text("\t\t\t“Agreement” shall mean and refer to this Terms of Service, including any amendments that may be incorporated into it."),
            Text("\t\t\t“Agreement Period” shall refer to the period for which the User engages the services of the Application."),
            Text("\t\t\t“Services” shall mean the services provided by the Company on the Application."),
            Text("\t\t\t“Third Party” shall mean and refer to any individual(s), company or entity apart from the User and the Company."),
            Text("\t\t\tThe headings of each section in this Agreement are only for the purpose of organising the various provisions under this Agreement in an orderly manner. These headings shall not be used by either party to interpret the provisions contained under them in any manner. Further, the headings have no legal or contractual value."),
            Text("\t\t\tBy using the Application, You accept and agree to be bound by this Agreement, the Privacy Policy, as well as rules, guidelines, policies, terms, and conditions applicable to any service that is provided by the Application that shall be deemed to be incorporated into this Agreement and shall be considered as part and parcel of this Agreement"),
            Text("\t\t\tYour use of Our Application is evidence that You have read and agreed to be contractually bound by these Agreement and Our Privacy Policy. Please read both carefully. The use of this Application by You is governed by this policy and any policy so mentioned by terms of reference."),
            Text(("\t\t\tIf You do not agree with any of these terms, please discontinue using the Application.")),
            Text(("\t\t\tWe hold the sole right to modify the Agreement without prior permission from You or providing notice to You. The relationship creates on You a duty to periodically check the Agreement and stay updated on its requirements. If You continue to use the Application or avail any of its Services without registration following such change, this is deemed as consent by You to the so amended policies. Your continued use of the Application is conditioned upon Your compliance with the Agreement, including but not limited to compliance with the Agreement even after alterations,if any.")),
            Text("\n\nAbout Us : ",style: TextStyle(fontWeight: FontWeight.bold,fontSize: 20),),
            Text("Owner & Developer : Darshan Bhalani"),
            Text("Email : darshanbhalanipatel@gmail.com"),
            Text("Phone : +91 9909343073"),
            Text("Support : support@metromate.in"),
            Text("Release Date : 01 Jan 2023"),
            Text("Version : v0.0.01")
          ],
        ),
      ),
    );
  }
}
